create database BlogDB
use BlogDB
CREATE TABLE Categories (
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(255)
)
CREATE TABLE Tags  (
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(255)
)
CREATE TABLE Users (
Id INT PRIMARY KEY IDENTITY(1,1),
UserName NVARCHAR(255) NOT NULL UNIQUE,
FullName NVARCHAR(255) NOT NULL,
Age INT NOT NULL CHECK (Age >= 0 AND Age <= 150)
);
CREATE TABLE Comments (
 Id INT PRIMARY KEY IDENTITY(1,1),
 Content NVARCHAR(250) NOT NULL,
 UserId int FOREIGN KEY REFERENCES Users(Id),
 BlogId int FOREIGN KEY REFERENCES Blogs(Id)
);
CREATE TABLE Blogs (
Id INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(50) NOT NULL,
Description NVARCHAR(1000) NOT NULL,
UserId int FOREIGN KEY  REFERENCES Users(Id),
CategoryId int FOREIGN KEY  REFERENCES Categories(Id)
);
CREATE TABLE BlogsTags (
Id INT PRIMARY KEY IDENTITY(1,1),
BlogsId int FOREIGN KEY  REFERENCES Blogs(Id),
TagsId int FOREIGN KEY  REFERENCES Tags(Id),
);

